### ISSUE TITLE
Creation of T_camX_velo all use R_rect_00

### ISSUE THREAD

**Issue by keenan-burnett** [utiasSTARS/pykitti#34]
This is what is instructed in the paper, but this seems like a typo?
I'm projecting the pointcloud onto the image plane for T_cam2_velo and I'm get slightly better results when using R_rect_20.

**Comment by leeclemnet** [comment]
I always thought this was strange, but the MATLAB devkit also uses `R_rect_00` for all the velodyne-to-camera transformations. What do you mean when you say you get better results? Do you also get improvements for cam1 and cam3?

**Comment by keenan-burnett** [comment]
Which MATLAB devkit are you referring to? It seems that the velodyne points, when projected onto camera 2, align slightly better when R_rect_20 is used. I looked at the other cameras as well. Similarly for camera 3, the point projection works better when using R_rect_30. Surprisingly, using P_rect_30, with T_cam2_velo and R_rect_20 resulted in the best projection for camera 3.

projection_onto_cam2_with_r_rect_00 (P_rect_20)
![projection_onto_cam2_with_r_rect_00](https://user-images.githubusercontent.com/9027562/47100187-f4966800-d204-11e8-8806-9a85bde7e3da.png)

projection_onto_cam2_with_r_rect_20 (P_rect_20)
![projection_onto_cam2_with_r_rect_20](https://user-images.githubusercontent.com/9027562/47100203-fc560c80-d204-11e8-8da2-1a272504a352.png)

projection_onto_cam3_with_t3_r_rect_00 (P_rect_30)
![projection_onto_cam3_with_t3_r_rect_00](https://user-images.githubusercontent.com/9027562/47100260-1e4f8f00-d205-11e8-913e-679ed8af3628.png)

projection_onto_cam3_with_t3_r_rect_30 (P_rect_30)
![projection_onto_cam3_with_t3_r_rect_30](https://user-images.githubusercontent.com/9027562/47100302-2ad3e780-d205-11e8-83e9-4569d22d9e6e.png)

projection_onto_cam3_with_t2_r_rect_20 (P_rect_30)
![projection_onto_cam3_with_t2_r_rect_20](https://user-images.githubusercontent.com/9027562/47100322-36271300-d205-11e8-8c65-dd377620b369.png)

**Comment by leeclemnet** [comment]
I'm referring to the raw data devkit provided on the [KITTI website](http://www.cvlibs.net/datasets/kitti/raw_data.php). If you look at the file `loadCalibration.m`, they've used `R_rect_00` everywhere. 

Looking at the [KITTI dataset IJRR paper](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf) again (Equations 5-7), this seems to be because the way they build up the velodyne to camera transformation is with the sequence velodyne-->unrectified cam0 coordinates-->rectified cam0 coordinates-->rectified camN coordinates. The transformation from unrectified cam0 coordinates-->rectified cam0 coordinates should always use `R_rect_00`. 

I think the improvements you're seeing might be coincidental, or else an artifact of imperfect calibration.

**Comment by keenan-burnett** [comment]
Okay, sounds good. Feel free to close.
