### ISSUE TITLE
Compute the velodyne to rectified camera coordinate transforms

### ISSUE THREAD

**Issue by C-MEN** [utiasSTARS/pykitti#35]
May I ask why transformation matrix for velodyne to camera **X** is 

data['T_cam**X**_velo'] = T**X**.dot(R_rect_00.dot(T_cam0unrect_velo))

instead of

data['T_cam**X**_velo'] = P_rect_**X0**.dot(R_rect_00.dot(T_cam0unrect_velo))  ?

**Comment by leeclemnet** [comment]
The matrix `P_rectX0` tells you the relationship between rectified 2D coordinates on the `cam0` image plane and rectified 2D coordinates on the `camX` image plane. If you look at Equation 4 in the [KITTI dataset IJRR paper](
http://www.cvlibs.net/publications/Geiger2013IJRR.pdf), you'll see that `P_rectX0` is made up of the pinhole camera intrinsics and the baseline of the stereo pair so that it can be used for this operation (Equations 5 & 7).

In contrast, `T_camXvelo` tells you the relationship between 3D coordinates in the `cam0` reference frame and 3D coordinates in the `camX` reference frame. You'll notice in the code that the transformation matrix `TX` is defined to be the identity matrix with a translation in the x-direction corresponding to the stereo baseline for the camera pair. The stereo baseline is easily recovered from `P_rectX0` by dividing two of its entries.
