### ISSUE TITLE
How to read the tracklets and get the box on image? (for both 2d and 3d)

### ISSUE THREAD

**Issue by lucasjinreal** [utiasSTARS/pykitti#36]
As title suggested

**Comment by dakdouky** [comment]
Same problem here! have you found a solution, @jinfagang ?

**Comment by leeclemnet** [comment]
Currently we only support the raw and odometry datasets. Support for the tracking dataset would be a nice addition if someone in the community wanted to tackle it and submit a PR.

**Comment by dakdouky** [comment]
I've managed to do it and will make it available soon.  thanks :) 
![untitled](https://user-images.githubusercontent.com/45735497/53610613-316f6400-3bd4-11e9-899f-6a60d03c62b7.png)

**Comment by leeclemnet** [comment]
Apparently I forgot about https://github.com/utiasSTARS/pykitti/pull/28, which added support for the tracking dataset. I haven't used it personally. Does it do what you need, or have you added something on top of it to get the bounding boxes?

**Comment by dakdouky** [comment]
In fact, I did not use it. Instead, I build some wrapping on top of Christian Herdtweck XML parser.
I'm trying to add a Dynamic/Static annotation to the tracklets.

**Comment by LukeAI** [comment]
Hey guys,
I want to be able to read the raw tracklets and extract the projected 2d bounding boxes and corresponding rgb image. I understand that this is possible with these utils but How can I do this?
@MOHAMEDELDAKDOUKY @leeclemnet

**Comment by DerekGloudemans** [comment]
I implemented bbox plotting for 2d and 3d objects for the tracking dataset. Will port it over to this repo and submit a pull request eventually. For now, the code is in: https://github.com/DerekGloudemans/KITTI-utils/blob/master/track_loader.py

Worth noting that the tracking dataset has very coarse object heights (I don't think they had people manually adjust the heights on this datset and the velodyne data perhaps doesn't contain this info because the objects extend above its range. I added a naive correction with a constant value for each class.
